/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacao;

import DAO.GatoDAO;
import DTO.GatoDTO;
import java.awt.FontFormatException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dsm2
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     *
     * @throws java.awt.FontFormatException
     * @throws java.io.IOException
     */
    public Cadastro() throws FontFormatException, IOException {
        initComponents(); // atenção! Esta linha já existe no seu JFrame       
    }
    GatoDTO cat = new GatoDTO();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boxPedigree = new javax.swing.JCheckBox();
        spinCrias = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdadeGato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeGato = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        cor = new javax.swing.JLabel();
        txtCR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRaca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rbAlto = new javax.swing.JRadioButton();
        rbMedia = new javax.swing.JRadioButton();
        rbBaixa = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        boxFemea = new javax.swing.JCheckBox();
        boxFemea1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JLabel();
        btnEstatistica = new javax.swing.JLabel();
        btnCfg = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 255, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NotClicked/homeNotClicked.png"))); // NOI18N
        btnHome.setToolTipText("");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeHomeClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, -1, -1));

        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cadastro.png"))); // NOI18N
        btnCadastro.setText("jLabel2");
        btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastroMouseExited(evt);
            }
        });
        jPanel2.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 334, 320, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo_branca(1) 1(2).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, 300, -1));

        jPanel3.setBackground(new java.awt.Color(13, 13, 14));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, -1, -1));

        jPanel1.setBackground(new java.awt.Color(53, 53, 53));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(53, 53, 53), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxPedigree.setBackground(new java.awt.Color(0, 0, 0));
        boxPedigree.setForeground(new java.awt.Color(255, 255, 255));
        boxPedigree.setText("Sim");
        boxPedigree.setContentAreaFilled(false);
        boxPedigree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPedigreeActionPerformed(evt);
            }
        });
        jPanel1.add(boxPedigree, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        spinCrias.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        spinCrias.setEnabled(false);
        jPanel1.add(spinCrias, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 102, 30));

        jPanel4.setBackground(new java.awt.Color(53, 53, 53));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 787, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Pedigree.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Group 18.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 72, -1, -1));

        txtIdadeGato.setBackground(new java.awt.Color(53, 53, 53));
        txtIdadeGato.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtIdadeGato.setForeground(new java.awt.Color(204, 204, 204));
        txtIdadeGato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtIdadeGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeGatoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdadeGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 350, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Idade estimada.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 170, -1));

        txtNomeGato.setBackground(new java.awt.Color(53, 53, 53));
        txtNomeGato.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtNomeGato.setForeground(new java.awt.Color(204, 204, 204));
        txtNomeGato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtNomeGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeGatoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomeGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 350, 30));

        txtCor.setBackground(new java.awt.Color(53, 53, 53));
        txtCor.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtCor.setForeground(new java.awt.Color(204, 204, 204));
        txtCor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });
        jPanel1.add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 180, 30));

        cor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cor.setForeground(new java.awt.Color(255, 255, 255));
        cor.setText("Cor");
        jPanel1.add(cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));

        txtCR.setBackground(new java.awt.Color(53, 53, 53));
        txtCR.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtCR.setForeground(new java.awt.Color(204, 204, 204));
        txtCR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(txtCR, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 230, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));

        txtRaca.setBackground(new java.awt.Color(53, 53, 53));
        txtRaca.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtRaca.setForeground(new java.awt.Color(204, 204, 204));
        txtRaca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(txtRaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 350, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Raça");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 50, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Niveis de atividades");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        rbAlto.setBackground(new java.awt.Color(0, 0, 0));
        rbAlto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbAlto.setForeground(new java.awt.Color(255, 255, 255));
        rbAlto.setText("Alta");
        rbAlto.setContentAreaFilled(false);
        rbAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAltoActionPerformed(evt);
            }
        });
        jPanel1.add(rbAlto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, -1, -1));

        rbMedia.setBackground(new java.awt.Color(0, 0, 0));
        rbMedia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbMedia.setForeground(new java.awt.Color(255, 255, 255));
        rbMedia.setText("Média");
        rbMedia.setContentAreaFilled(false);
        rbMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMediaActionPerformed(evt);
            }
        });
        jPanel1.add(rbMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 690, -1, -1));

        rbBaixa.setBackground(new java.awt.Color(0, 0, 0));
        rbBaixa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbBaixa.setForeground(new java.awt.Color(255, 255, 255));
        rbBaixa.setText("Baixa");
        rbBaixa.setContentAreaFilled(false);
        rbBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBaixaActionPerformed(evt);
            }
        });
        jPanel1.add(rbBaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 720, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(255, 191, 27));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar e continuar");
        btnSalvar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 191, 27), 5, true));
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 870, 220, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Histórico Reprodutivo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        txtObs.setBackground(new java.awt.Color(53, 53, 53));
        txtObs.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtObs.setForeground(new java.awt.Color(204, 204, 204));
        txtObs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(txtObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 250, 180));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Observação");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 100, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Nome.png"))); // NOI18N
        jLabel13.setText("jLabel2");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 50, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Group 19.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 130, 170));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("É femea?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Detalhes básicos - Gato");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        boxFemea.setForeground(new java.awt.Color(255, 255, 255));
        boxFemea.setText("Sim");
        boxFemea.setContentAreaFilled(false);
        boxFemea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFemeaActionPerformed(evt);
            }
        });
        jPanel1.add(boxFemea, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, -1, -1));

        boxFemea1.setForeground(new java.awt.Color(255, 255, 255));
        boxFemea1.setText("Sim");
        boxFemea1.setContentAreaFilled(false);
        boxFemea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFemea1ActionPerformed(evt);
            }
        });
        jPanel1.add(boxFemea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1250, 1100));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NotClicked/RelatorionotClicked.png"))); // NOI18N
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerfilMouseExited(evt);
            }
        });

        btnEstatistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NotClicked/estatisticasNotClicked.png"))); // NOI18N
        btnEstatistica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstatisticaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstatisticaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstatisticaMouseExited(evt);
            }
        });

        btnCfg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NotClicked/configuraçaoNotClicked.png"))); // NOI18N
        btnCfg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCfgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCfgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCfgMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstatistica, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCfg, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(btnPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstatistica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCfg)
                .addContainerGap(480, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 1100));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBaixaActionPerformed

    private void rbAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAltoActionPerformed

    private void rbMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMediaActionPerformed

    private void boxPedigreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPedigreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPedigreeActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        cadastrarGato();
       
         

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        // TODO add your handling code here:

        dispose();
        CadastroDono cadd = new CadastroDono();
        new CadastroDono().setVisible(true);
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtIdadeGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeGatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeGatoActionPerformed

    private void txtNomeGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeGatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeGatoActionPerformed

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void btnCfgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCfgMouseExited
        // TODO add your handling code here:

        btnCfg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NotClicked/configuraçaoNotClicked.png")));
    }//GEN-LAST:event_btnCfgMouseExited

    private void btnCfgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCfgMouseEntered
        // TODO add your handling code here:

        btnCfg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/configuraçao.png")));
    }//GEN-LAST:event_btnCfgMouseEntered

    private void btnEstatisticaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatisticaMouseExited
        // TODO add your handling code here:

        btnEstatistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NotClicked/estatisticasNotClicked.png")));
    }//GEN-LAST:event_btnEstatisticaMouseExited

    private void btnEstatisticaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatisticaMouseEntered
        // TODO add your handling code here:

        btnEstatistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/estatisticasClicked.png")));
    }//GEN-LAST:event_btnEstatisticaMouseEntered

    private void btnPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseExited
        // TODO add your handling code here:

        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NotClicked/RelatorionotClicked.png")));
    }//GEN-LAST:event_btnPerfilMouseExited

    private void btnPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseEntered
        // TODO add your handling code here:

        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Relatorioclicked.png")));
    }//GEN-LAST:event_btnPerfilMouseEntered

    private void btnCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCadastroMouseExited

    private void btnCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseEntered
        // TODO add your handling code here:

        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cadastro.png")));
    }//GEN-LAST:event_btnCadastroMouseEntered

    private void btnCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroMouseClicked

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/NotClicked/homeNotClicked.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/homeClicked.png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeHomeClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeHomeClicked
        // TODO add your handling code here:

        dispose();
        PaginaInicial pg = new PaginaInicial();
        pg.setVisible(true);
        
    }//GEN-LAST:event_btnHomeHomeClicked

    private void boxFemeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFemeaActionPerformed
        // TODO add your handling code here:
        
        spinCrias.setEnabled(true);
        
    }//GEN-LAST:event_boxFemeaActionPerformed

    private void boxFemea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFemea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxFemea1ActionPerformed

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        // TODO add your handling code here:
        
        dispose();
        try {
            new Relatorio().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PaginaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnEstatisticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatisticaMouseClicked
        // TODO add your handling code here:
        dispose();
        new Estatistica().setVisible(true);
       
    }//GEN-LAST:event_btnEstatisticaMouseClicked

    private void btnCfgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCfgMouseClicked
        // TODO add your handling code here:
         dispose();
        Config conf = new Config();
        conf.setVisible(true);
    }//GEN-LAST:event_btnCfgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Cadastro().setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxFemea;
    private javax.swing.JCheckBox boxFemea1;
    private javax.swing.JCheckBox boxPedigree;
    private javax.swing.JLabel btnCadastro;
    private javax.swing.JLabel btnCfg;
    private javax.swing.JLabel btnEstatistica;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnPerfil;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel cor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton rbAlto;
    private javax.swing.JRadioButton rbBaixa;
    private javax.swing.JRadioButton rbMedia;
    private javax.swing.JSpinner spinCrias;
    private javax.swing.JTextField txtCR;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtIdadeGato;
    private javax.swing.JTextField txtNomeGato;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtRaca;
    // End of variables declaration//GEN-END:variables

    public void cadastrarGato() {
        String nomeGato, pedigree, raca, nivel_atividade, cor, gatoFemea, obs;
        int idadeGato, crGato, quantidade_filhos;

        nomeGato = txtNomeGato.getText();
        raca = txtRaca.getText();
        cor = txtCor.getText();
        obs = txtObs.getText();
        idadeGato = Integer.parseInt(txtIdadeGato.getText());
        crGato = Integer.parseInt(txtCR.getText());

        if (rbBaixa.isSelected()) {
            cat.setNivelAtividade("Baixa");
        } else if (rbMedia.isSelected()) {
            cat.setNivelAtividade("Média");
        } else if (rbAlto.isSelected()) {
            cat.setNivelAtividade("Alta");
        }

        if (rbBaixa.isSelected()) {
            cat.setNivelAtividade("Baixa");
        } else if (rbMedia.isSelected()) {
            cat.setNivelAtividade("Média");
        } else if (rbAlto.isSelected()) {
            cat.setNivelAtividade("Alta");
        }

        int quantidadeFilhos = (int) spinCrias.getValue();
        cat.setQuantidadeFilhos(quantidadeFilhos);

        boolean isPedigree = boxPedigree.isSelected();
        cat.setPedigree(isPedigree);

        boolean isGatoFemea = boxFemea.isSelected();
        cat.setGatoFemea(isGatoFemea);

        cat.setNome(nomeGato);
        cat.setRaça(raca);
        cat.setCor(cor);
        cat.setObs(obs);
        cat.setIdade(idadeGato);
        cat.setcR(crGato);

        GatoDAO objgatodao = new GatoDAO();
        objgatodao.cadastrarGato(cat);
    }

}
